DO $$
DECLARE
  v_user_id UUID := gen_random_uuid();
  v_email TEXT := 'superadmin@capacityconnect.com';
  v_password TEXT := '12345678';
BEGIN
  -- 1. Create a brand new, clean user
  INSERT INTO auth.users (
    id, instance_id, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
    role, confirmation_token, recovery_token, email_change_token_new, email_change
  ) VALUES (
    v_user_id, '00000000-0000-0000-0000-000000000000', v_email,
    crypt(v_password, gen_salt('bf')), now(),
    '{"provider": "email", "providers": ["email"]}',
    jsonb_build_object('full_name', 'System Super Admin', 'role', 'super_admin'),
    now(), now(), 'authenticated', '', '', '', ''
  );

  -- 2. Update the profile that was automatically generated by your database triggers
  UPDATE public.profiles 
  SET 
    role = 'super_admin',
    approval_status = 'approved',
    full_name = 'System Super Admin'
  WHERE id = v_user_id;
  
END $$;
